Repository stefanDeveloper/heiDGAF, pull requests merged in 2024-10, with the labels that each got.

#36 Add `pre-commit` check
  .github/workflows/build_test_linux.yml
  .github/workflows/build_test_macos.yml
  .github/workflows/build_test_windows.yml
  .github/workflows/cleanup.yml
  .github/workflows/formatting.yml
  .github/workflows/test_coverage.yml
  .readthedocs.yml
  README.md
  docs/api/index.rst
  docs/conf.py
  docs/index.rst
  docs/pipeline.rst
  docs/requirements.txt
  docs/training.rst
  docs/usage.rst
  requirements/requirements.dev.txt
  requirements/requirements.train.txt
  src/base/logline_handler.py
  src/base/utils.py
  src/detector/detector.py
  src/inspector/inspector.py
  src/logcollector/batch_handler.py
  src/logcollector/collector.py
  src/logserver/server.py
  tests/test_batch_handler.py
  tests/test_collector.py
  tests/test_detector.py
  tests/test_field_type.py
  tests/test_inspector.py
  tests/test_kafka_consume_handler.py
  tests/test_kafka_handler.py
  tests/test_kafka_produce_handler.py
  tests/test_marshmallow.py
  tests/test_prefilter.py
  tests/test_server.py
  tests/test_utils.py
Labels: enhancement

#35 Add coverage badge
  .github/workflows/test_coverage.yml
  README.md
  assets/upload_seafile.py
Labels: enhancement

#37 Update configuration
  config.yaml
  docs/configuration.rst
  docs/usage.rst
  src/base/kafka_handler.py
  src/base/log_config.py
  src/base/logline_handler.py
  src/base/utils.py
  src/detector/detector.py
  src/inspector/inspector.py
  src/logcollector/batch_handler.py
  src/logcollector/collector.py
  src/logserver/server.py
  src/mock/generator.py
  src/prefilter/prefilter.py
  tests/test_log_config.py
  tests/test_logline_handler.py
Labels: documentation, enhancement

#42 Fix kafka warnings
  docker/docker-compose.kafka.yml
  docker/docker-compose.yml
Labels: bug

#40 Add docstrings and fix closing of LogServer
  src/logserver/server.py
  src/prefilter/prefilter.py
Labels: bug, documentation

#47 Add shell script that installs all requirements
  README.md
  install_requirements.sh
Labels: enhancement
