Repository stefanDeveloper/heiDGAF, pull requests merged in 2025-04, with the labels that each got.

#73 Update collector
  src/logcollector/collector.py
  src/monitoring/clickhouse_batch_sender.py
  tests/clickhouse/test_clickhouse_batch_sender.py
  tests/logcollector/test_collector.py
Labels: bug, enhancement

#74 Update missing docstrings or docstrings with too few information
  src/base/clickhouse_kafka_sender.py
  src/base/data_classes/batch.py
  src/base/kafka_handler.py
  src/detector/detector.py
  src/inspector/inspector.py
  src/logcollector/batch_handler.py
  src/monitoring/clickhouse_batch_sender.py
  src/train/model.py
Labels: documentation

#76 Improve Inspector performance
  src/inspector/inspector.py
  tests/inspector/test_inspector.py
Labels: enhancement
